---
 - hosts: webservers
   user: jenkins
   tasks: 
   # - name : Verification service docker
   #   service: name=docker state=started enabled= yes

   #  - name : Installation wgett
   #    yum: name=wget state=latest
     - name :  Service Status
       service: name=docker state=started
     - name : Installation java8 - 1er etape
       yum: name=java-openjdk-devel state=latest
     - name : Installation java8 - 2eme etape
       yum: name=java-openjdk state=latest

